// Lenguajes Interpretados/Parcial 4/examen/src/routes/Contact.svelte
<section class="contact section" id="contact">
    <div class="container">
        <div class="row">
            <div class="section-title padd-15">
                <h2>Contact</h2>
            </div>
        </div>
        <h3 class="contact-title padd-15">Have You Any Questions ?</h3>
        <h4 class="contact-sub-title padd-15">CONTACT ME</h4>
        <div class="row">
            <!-- ===== Contact info item start ===== -->
            <div class="contact-info-item padd-15">
                <div class="icon"><i class="fa fa-phone"></i></div>
                    <h4>Phone</h4>
                <p>(669) 212 7762</p>
            </div>
            <!-- ===== Contact info item End ===== -->
            <!-- ===== Contact info item start ===== -->
            <div class="contact-info-item padd-15">
                <div class="icon"><i class="fa fa-envelope"></i></div>
                    <h4>Email</h4>
                <p>Juanfernand2004@hotmail.com</p>
            </div>
        <!-- ===== Contact info item End ===== -->
            <!-- ===== Contact info item start ===== -->
            <div class="contact-info-item padd-15">
                <a href="https://www.linkedin.com/in/juan-fernando-aispuro-05008b224/" target="_blank">
                    <div class="icon"><i class="fa fab fa-linkedin" aria-hidden="true"></i></div>
                        <h4 class="links">Linkedin</h4>
                    <p>Juanfer Aispuro</p>
                </a>
            </div>
            <!-- ===== Contact info item End ===== -->
            <!-- ===== Contact info item start ===== -->
            <div class="contact-info-item padd-15">
                <a href="https://github.com/Juanf4r" target="_blank">
                    <div class="icon"><i class="fa fab fa-github"></i></div>
                        <h4 class="links">Github</h4>
                    <p>Juanf4r</p>
                </a>
            </div>
            <!-- ===== Contact info item End ===== -->
        </div>
        <h3 class="contact-title padd-15">SEND ME A MESSAGE</h3>
        <h4 class="contact-sub-title padd-15">I'M VERY RESPONSIVE</h4>
        <!-- ===== Contact Form ===== -->
        <form action="https://formsubmit.co/juanfernand2004@hotmail.com" target="_blank" method="POST">
            <div class="row">
                <div class="contact-form padd-15">
                    <div class="row">
                        <div class="form-item col-6 padd-15">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Full Name" required>
                            </div>
                        </div>
                        <div class="form-item col-6 padd-15">
                            <div class="form-group">
                                <input type="email" name="email" class="form-control" placeholder="Email Address" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-item col-12 padd-15">
                            <div class="form-group">
                                <input type="text" name="" class="form-control" placeholder="Subject" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-item col-12 padd-15">
                            <div class="form-group">
                                <textarea name ="message" placeholder ="Your Message" class = "form-control" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-item col-12 padd-15">
                            <button type="submit" class="btn">SUBMIT MESSAGE</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <footer>
        <p class="footer">Created by JuanFer Aispuro Sanchez</p>
    </footer>
</section>

// Lenguajes Interpretados/Parcial 2/Examen Portfolio/src/pages/Contact.tsx
function Contact() {
  return (
<section className="contact section" id="contact">
    <div className="container">
        <div className="row">
            <div className="section-title padd-15">
                <h2>Contact Me</h2>
            </div>
        </div>
        <h3 className="contact-title padd-15">Have You Any Questions ?</h3>
        <h4 className="contact-sub-title padd-15">I'M AT YOUR SERVICES</h4>
        <div className="row">
            {/* <!-- ===== Contact info item start ===== --> */}
            <div className="contact-info-item padd-15">
                <div className="icon"><i className="fa fa-phone"></i></div>
                <h4>Call Me</h4>
                <p>+52 669 212 7762</p>
            </div>
            {/* <!-- ===== Contact info item End ===== --> */}
            {/* <!-- ===== Contact info item start ===== --> */}
            <div className="contact-info-item padd-15">
                <div className="icon"><i className="fa fa-map-marker-alt"></i></div>
                <h4>Office</h4>
                <p>Zapopan, Jalisco</p>
            </div>
            {/* <!-- ===== Contact info item End ===== --> */}
            {/* <!-- ===== Contact info item start ===== --> */}
            <div className="contact-info-item padd-15">
                <div className="icon"><i className="fa fa-envelope"></i></div>
                <h4>Email</h4>
                <p>Juanfernand2004@hotmail.com</p>
            </div>
            {/* <!-- ===== Contact info item End ===== --> */}
            {/* <!-- ===== Contact info item start ===== --> */}
            <div className="contact-info-item padd-15">
                <div className="icon"><i className="fa fa-globe-europe"></i></div>
                <h4>website</h4>
                <p>juanf4r.github.io</p>
            </div>
            {/* <!-- ===== Contact info item End ===== --> */}
        </div>
        <h3 className="contact-title padd-15">SEND ME A MESSAGE</h3>
        <h4 className="contact-sub-title padd-15">I'M VERY RESPONSIVE</h4>
        {/* <!-- ===== Contact Form ===== --> */}
        <form action="https://formsubmit.co/juanfernand2004@hotmail.com" method="POST">
            <div className="row">
                <div className="contact-form padd-15">
                    <div className="row">
                        <div className="form-item col-6 padd-15">
                            <div className="form-group">
                                <input type="text" name="name" className="form-control" placeholder="Full Name" required></input>
                            </div>
                        </div>
                        <div className="form-item col-6 padd-15">
                            <div className="form-group">
                                <input type="email" name="email" className="form-control" placeholder="Email Address" required></input>
                            </div>
                        </div>
                    </div>
                    <div className="row">
                        <div className="form-item col-12 padd-15">
                            <div className="form-group">
                                <input type="text" name="" className="form-control" placeholder="Subject" required></input>
                            </div>
                        </div>
                    </div>
                    <div className="row">
                        <div className="form-item col-12 padd-15">
                            <div className="form-group">
                                <textarea name ="message" placeholder ="Your Message" className = "form-control" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div className="row">
                        <div className="form-item col-12 padd-15">
                            <button type="submit" className="btn">SUBMIT MESSAGE</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <footer>
        <p className="footer">Created by JuanFer Aispuro Sanchez</p>
    </footer>
</section>

)}

export default Contact
