// Lenguajes Interpretados/Parcial 4/Portfolio Svelte/src/lib/Portfolio.svelte
<section class="portfolio section" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="section-title padd-15">
                <h2>Portfolio</h2>
            </div>
        </div>
        <div class="row">
            <div class="portfolio-heading padd-15">
                <h2>My Last Projects</h2>
            </div>
        </div>
        <div class="row">
            <!-- ===== portfolio item Start =====-->
            <div class="portfolio-item padd-15">
                <h2 class="title">Tap to Stream!</h2>
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <a href="https://play.google.com/store/apps/details?id=com.Juanfer.Taptostream" target="_blank" tabIndex="0">
                            <img src="/imagen1.avif" alt="">
                            <img class="bn45" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Google_Play_Store_badge_EN.svg/2560px-Google_Play_Store_badge_EN.svg.png" alt="bn45"/>
                        </a>
                    </div>
                </div>
            </div>
            <div class="portfolio-item padd-15">
                <h2 class="title">Fish & Waste</h2>
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <a href="https://juanf4r-dev.itch.io/fish-and-waste" target="_blank" tabIndex="0">
                            <img src="/imagen2.avif" alt="">
                            <img class="bn45" src= "/itch.svg" alt="bn45"/>
                        </a>
                    </div>
                </div>
            </div>
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div class="portfolio-item padd-15">
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <img src="img/imagen3.jpg" alt="">
                    </div>
                </div>
            </div> -->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div class="portfolio-item padd-15">
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <img src="img/imagen4.jpg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div class="portfolio-item padd-15">
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <img src="img/imagen5.jpg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div class="portfolio-item padd-15">
                <div class="portfolio-item-inner shadow-dark">
                    <div class="portfolio-img">
                        <img src="img/imagen6.jpeg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
        </div>
    </div>
</section>

// Lenguajes Interpretados/Parcial 2/Examen Portfolio/src/pages/Portfolio.tsx
function Portfolio(){
return (
<section className="portfolio section" id="portfolio">
    <div className="container">
        <div className="row">
            <div className="section-title padd-15">
                <h2>Portfolio</h2>
            </div>
        </div>
        <div className="row">
            <div className="portfolio-heading padd-15">
                <h2>My Last Projects</h2>
            </div>
        </div>
        <div className="row">
            {/* <!-- ===== portfolio item Start =====--> */}
            <div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <a href="https://play.google.com/store/apps/details?id=com.Juanfer.Taptostream&hl=es_419&gl=US" target="_blank">
                            <img src="public/img/imagen1.png" alt=""></img>
                        </a>
                    </div>
                </div>
            </div>
            {/* <!-- ===== portfolio item End =====--> */}
            {/* <!-- ===== portfolio item Start =====--> */}
            {/* <!--<div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <img src="img/imagen2.jpeg" alt=""></img>
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <img src="img/imagen3.jpg" alt="">
                    </div>
                </div>
            </div> -->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <img src="img/imagen4.jpg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <img src="img/imagen5.jpg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====-->
            <!-- ===== portfolio item Start =====-->
            <!--<div className="portfolio-item padd-15">
                <div className="portfolio-item-inner shadow-dark">
                    <div className="portfolio-img">
                        <img src="img/imagen6.jpeg" alt="">
                    </div>
                </div>
            </div>-->
            <!-- ===== portfolio item End =====--> */}
        </div>
    </div>
</section>
)}

export default Portfolio
