// Lenguajes Interpretados/Parcial 4/examen/src/lib/Aside.svelte
<script>
    import Section from "../routes/Section.svelte";
    import Router from 'svelte-spa-router' 
    import {push} from 'svelte-spa-router'
    import routes from '../routes.js'
    import Home from "../routes/Section.svelte";
    import About from "../routes/AboutSection.svelte";
    import Services from "../routes/Services.svelte";
    import Portfolio from "../routes/Portfolio.svelte";
    import Contact from "../routes/Contact.svelte";
</script>

<div class="aside">
    <div class="logo">
        <span>Juanfer</span>Dev
    </div>
    <div class="nav-toggler">
        <span></span>
    </div>
    <ul class="nav">
        <nav>
            <li><button on:click={()=>push("/")}  class="active"><i class="fa fa-home"></i> Home</button></li>
            <li><button on:click={()=>push("/about")} ><i class="fa fa-user"></i> About</button></li>
            <li><button on:click={()=>push("/skills")}><i class="fa fa-list"></i>Skills</button></li>
            <li><button on:click={()=>push("/portfolio")}><i class="fa fa-briefcase"></i>Portfolio</button></li>
            <li><button on:click={()=>push("/contact")}><i class="fa fa-comments"></i>Contact</button></li>
        </nav>
    </ul>

    <Router {routes} />

</div>

// Lenguajes Interpretados/Parcial 2/Examen Portfolio/src/router/Aside.tsx
import { Link } from "react-router-dom"

const Aside = () => {
return (
        <div className="aside">
            <div className="logo">
                <a href="#"><span>Juanfer</span>Dev</a>
            </div>
            <div className="nav-toggler">
                <span></span>
            </div>
            <ul className="nav">
                <li><Link to={"/home"}></Link><a className="active"><i className="fa fa-home"></i>Home</a></li>
                <li><Link to={"/about"}></Link><a href="#about"><i className="fa fa-user"></i>About</a></li>
                <li><Link to={"/skills"}></Link><a href="#services"><i className="fa fa-list"></i>Skills</a></li>
                <li><Link to={"/portfolio"}></Link><a href="#portfolio"><i className="fa fa-briefcase"></i>Portfolio</a></li>
                <li><Link to={"/contact"}></Link><a href="#contact"><i className="fa fa-comments"></i>Contact</a></li>
            </ul>
        </div>
)}

export default Aside
