// Lenguajes Interpretados/Parcial 2/Examen Portfolio/src/pages/Services.tsx
function Services() {
return(
                <section className="service section" id="services">
                    <div className="container">
                        <div className="row">
                            <div className="section-title padd-15">
                                <h2>Skills</h2>
                            </div>
                        </div>
                        <div className="row">
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fab fa-free-code-camp"></i>
                                    </div>
                                    <h4>C++</h4>
                                    <p>1 Year & 6 Months of Experience on Development in console applications projects.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fa-gamepad"></i>
                                    </div>
                                    <h4>C# Unity</h4>
                                    <p>1 Year of Experience on Game Development, creating 2D Games for Mobile and Pc.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fab fa-python"></i>
                                    </div>
                                    <h4>Python</h4>
                                    <p>Just starting, Very Enthusiastic to learn Python for Web Development and Console Applications Projects.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fa-code"></i>
                                    </div>
                                    <h4>HTML/CSS/JavaScript</h4>
                                    <p>1 Year of Experience on Front end Development, creating templates and updating my Portfolio.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fa-mobile-alt"></i>
                                    </div>
                                    <h4>Flutter</h4>
                                    <p>Just starting, Very Enthusiastic to learn Dart for App Development for ios and Android.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                            {/* <!-- ===== Service item Start ===== --> */}
                            <div className="service-item padd-15">
                                <div className="service-item-inner">
                                    <div className="icon">
                                        <i className="fa fa-server"></i>
                                    </div>
                                    <h4>Java</h4>
                                    <p>Just starting, Very Enthusiastic to learn Java to create Minecraft Mods and Servers.
                                    </p>
                                </div>
                            </div>
                            {/* <!-- ===== Service item End ===== --> */}
                        </div>
                    </div>
                </section>
)}

export default Services

// Lenguajes Interpretados/Parcial 4/examen/src/routes/Services.svelte
<section class="service section" id="services">
    <div class="container">
        <div class="row">
            <div class="section-title padd-15">
                <h2>Skills</h2>
            </div>
        </div>
        <div class="row">
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fab fa-free-code-camp"></i>
                    </div>
                    <h4>C++</h4>
                    <p>1 Year & 6 Months of Experience on Development in console applications projects.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fa-gamepad"></i>
                    </div>
                    <h4>C# Unity</h4>
                    <p>1 Year of Experience on Game Development, creating 2D Games for Mobile and Pc.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fab fa-python"></i>
                    </div>
                    <h4>Python</h4>
                    <p>Just starting, Very Enthusiastic to learn Python for Web Development and Console Applications Projects.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fa-code"></i>
                    </div>
                    <h4>HTML/CSS/JavaScript</h4>
                    <p>1 Year of Experience on Front end Development, creating templates and updating my Portfolio.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fa-mobile-alt"></i>
                    </div>
                    <h4>Flutter</h4>
                    <p>Just starting, Very Enthusiastic to learn Dart for App Development for ios and Android.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
            <!-- ===== Service item Start ===== -->
            <div class="service-item padd-15">
                <div class="service-item-inner">
                    <div class="icon">
                        <i class="fa fa-server"></i>
                    </div>
                    <h4>Java</h4>
                    <p>Just starting, Very Enthusiastic to learn Java to create Minecraft Mods and Servers.
                    </p>
                </div>
            </div>
            <!-- ===== Service item End ===== -->
        </div>
    </div>
</section>
